# Generated by Django 3.0.7 on 2020-06-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=100)),
                ('img_name', models.CharField(default='', max_length=50)),
                ('img_desc', models.CharField(default='', max_length=500)),
                ('img', models.ImageField(default='', upload_to='post/images')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
