# Generated by Django 3.0.7 on 2020-06-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_pic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pic',
            name='web_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
