# Generated by Django 3.0.7 on 2020-06-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_pic', '0002_auto_20200619_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='category',
            new_name='tags',
        ),
    ]
