# Generated by Django 3.0.7 on 2020-06-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_pic', '0003_auto_20200619_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=500)),
                ('comment_pic', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
