# Generated by Django 3.0.7 on 2020-06-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=500)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
